// import localFont from "next/font/local";
import "./globals.css";
// import {poppins} from '@next/font/google'

// import Header from './components/header'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import Header from './components/header.jsx'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      {/* <Poppins/> */}
      <Header/>
        {children}
      </body>
    </html>
  );
}
